{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "2d72b689",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-10-17T19:04:47.128071Z",
     "start_time": "2025-10-17T19:04:47.121019Z"
    }
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'c:\\\\Users\\\\gimep\\\\Downloads\\\\workspace\\\\text_summarizer\\\\research'"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import os\n",
    "%pwd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "214fb151",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-10-17T19:04:47.155891Z",
     "start_time": "2025-10-17T19:04:47.148880Z"
    }
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'C:\\\\Users\\\\gimep\\\\Downloads\\\\workspace\\\\text_summarizer'"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "os.chdir(r\"C:/Users/gimep/Downloads/workspace/text_summarizer/\")\n",
    "%pwd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "31c7dd99",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-10-17T19:04:47.210448Z",
     "start_time": "2025-10-17T19:04:47.205558Z"
    }
   },
   "outputs": [],
   "source": [
    "from dataclasses import dataclass\n",
    "from pathlib import Path"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "1c170f38",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-10-17T19:04:47.237706Z",
     "start_time": "2025-10-17T19:04:47.233162Z"
    }
   },
   "outputs": [],
   "source": [
    "@dataclass\n",
    "class DataIngestionConfig:\n",
    "    root_dir: Path\n",
    "    source_URL: Path\n",
    "    local_data_file: Path\n",
    "    unzip_dir: Path"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "ec4acce0",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-10-17T19:04:47.247139Z",
     "start_time": "2025-10-17T19:04:47.242627Z"
    }
   },
   "outputs": [],
   "source": [
    "from src.textsummarizer.constants import *\n",
    "from src.textsummarizer.utils.common import read_yaml, create_directories"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "2dea86c5a299a75b",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-10-17T19:04:47.258200Z",
     "start_time": "2025-10-17T19:04:47.254252Z"
    }
   },
   "outputs": [],
   "source": [
    "# Configuration Updates"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "03315dfa",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-10-17T19:04:47.270451Z",
     "start_time": "2025-10-17T19:04:47.265572Z"
    }
   },
   "outputs": [],
   "source": [
    "class ConfigurationManager():\n",
    "    def __init__(self, config_path=CONFIG_FILE_PATH,\n",
    "                    params_path=PARAMS_FILE_PATH):\n",
    "        self.config=read_yaml(config_path)\n",
    "        self.params=read_yaml(params_path)\n",
    "        create_directories([self.config.artifacts_root])\n",
    "\n",
    "    def get_data_ingestion_config(self) -> DataIngestionConfig:\n",
    "        config=self.config.data_ingestion\n",
    "        create_directories([config.root_dir])\n",
    "        data_ingestion_config=DataIngestionConfig(\n",
    "            root_dir=config.root_dir,\n",
    "            source_URL=config.source_URL,\n",
    "            local_data_file=config.local_data_file,\n",
    "            unzip_dir=config.unzip_dir\n",
    "        )\n",
    "        return data_ingestion_config"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "3d837db5",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-10-17T19:04:47.280785Z",
     "start_time": "2025-10-17T19:04:47.275537Z"
    }
   },
   "outputs": [],
   "source": [
    "import os\n",
    "import urllib.request as request\n",
    "import zipfile\n",
    "from src.textsummarizer.logging import logger\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "f3500a68c84ed8a0",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-10-17T19:04:47.293149Z",
     "start_time": "2025-10-17T19:04:47.286792Z"
    }
   },
   "outputs": [],
   "source": [
    "class DataIngestion:\n",
    "    def __init__(self,config:DataIngestionConfig):\n",
    "        self.config=config\n",
    "\n",
    "    def download_file(self):\n",
    "        if not os.path.exists(self.config.local_data_file):\n",
    "            filename, headers = request.urlretrieve(\n",
    "                url = self.config.source_URL,\n",
    "                filename = self.config.local_data_file\n",
    "            )\n",
    "            logger.info(f\"File is downloaded\")\n",
    "        else:\n",
    "            logger.info(f\"File already exits\")\n",
    "\n",
    "    def extract_zip_file(self):\n",
    "        \"\"\"\n",
    "        zip_file_path: str\n",
    "        Extracts the zip file into the data directory\n",
    "        Function returns None\n",
    "        \"\"\"\n",
    "        unzip_path = self.config.unzip_dir\n",
    "        os.makedirs(unzip_path, exist_ok=True)\n",
    "        with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:\n",
    "            zip_ref.extractall(unzip_path)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7eb800721261e317",
   "metadata": {},
   "source": [
    "Components"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "f09e1c8544e7f881",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-10-17T19:04:47.302677Z",
     "start_time": "2025-10-17T19:04:47.299798Z"
    }
   },
   "outputs": [],
   "source": [
    "#Components"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "c1e180094b7faee",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-10-17T19:04:47.317612Z",
     "start_time": "2025-10-17T19:04:47.308356Z"
    }
   },
   "outputs": [],
   "source": [
    "class DataIngestion:\n",
    "    def __init__(self,config:DataIngestionConfig):\n",
    "        self.config=config\n",
    "\n",
    "    def download_file(self):\n",
    "        if not os.path.exists(self.config.local_data_file):\n",
    "            filename, headers = request.urlretrieve(\n",
    "                url = self.config.source_URL,\n",
    "                filename = self.config.local_data_file\n",
    "            )\n",
    "            logger.info(f\"File is downloaded\")\n",
    "        else:\n",
    "            logger.info(f\"File already exits\")\n",
    "\n",
    "    def extract_zip_file(self):\n",
    "        \"\"\"\n",
    "        zip_file_path: str\n",
    "        Extracts the zip file into the data directory\n",
    "        Function returns None\n",
    "        \"\"\"\n",
    "        unzip_path = self.config.unzip_dir\n",
    "        os.makedirs(unzip_path, exist_ok=True)\n",
    "        with zipfile.ZipFile(self.config.local_data_file, 'r') as zip_ref:\n",
    "            zip_ref.extractall(unzip_path)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "a582d377c6be9107",
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-10-17T19:04:47.504263Z",
     "start_time": "2025-10-17T19:04:47.327042Z"
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 690, in format\n",
      "    s = self.formatMessage(record)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 659, in formatMessage\n",
      "    return self._style.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 449, in format\n",
      "    return self._format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 445, in _format\n",
      "    return self._fmt % values\n",
      "           ~~~~~~~~~~^~~~~~~~\n",
      "ValueError: unsupported format character ':' (0x3a) at index 26\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 758, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 701, in shell_main\n",
      "    await self.dispatch_shell(msg, subshell_id=subshell_id)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 469, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 379, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 899, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 471, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 632, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\gimep\\AppData\\Local\\Temp\\ipykernel_14656\\32785271.py\", line 1, in <module>\n",
      "    config=ConfigurationManager()\n",
      "  File \"C:\\Users\\gimep\\AppData\\Local\\Temp\\ipykernel_14656\\1310873614.py\", line 4, in __init__\n",
      "    self.config=read_yaml(config_path)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ensure\\main.py\", line 849, in __call__\n",
      "    return_val = self.f(*args, **kwargs)\n",
      "  File \"C:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\src\\textsummarizer\\utils\\common.py\", line 27, in read_yaml\n",
      "    logger.info(f\"yaml file: {path_to_yaml} loaded successfully\")\n",
      "Message: 'yaml file: config\\\\config.yaml loaded successfully'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 690, in format\n",
      "    s = self.formatMessage(record)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 659, in formatMessage\n",
      "    return self._style.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 449, in format\n",
      "    return self._format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 445, in _format\n",
      "    return self._fmt % values\n",
      "           ~~~~~~~~~~^~~~~~~~\n",
      "ValueError: unsupported format character ':' (0x3a) at index 26\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 758, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 701, in shell_main\n",
      "    await self.dispatch_shell(msg, subshell_id=subshell_id)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 469, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 379, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 899, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 471, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 632, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\gimep\\AppData\\Local\\Temp\\ipykernel_14656\\32785271.py\", line 1, in <module>\n",
      "    config=ConfigurationManager()\n",
      "  File \"C:\\Users\\gimep\\AppData\\Local\\Temp\\ipykernel_14656\\1310873614.py\", line 4, in __init__\n",
      "    self.config=read_yaml(config_path)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ensure\\main.py\", line 849, in __call__\n",
      "    return_val = self.f(*args, **kwargs)\n",
      "  File \"C:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\src\\textsummarizer\\utils\\common.py\", line 27, in read_yaml\n",
      "    logger.info(f\"yaml file: {path_to_yaml} loaded successfully\")\n",
      "Message: 'yaml file: config\\\\config.yaml loaded successfully'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 690, in format\n",
      "    s = self.formatMessage(record)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 659, in formatMessage\n",
      "    return self._style.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 449, in format\n",
      "    return self._format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 445, in _format\n",
      "    return self._fmt % values\n",
      "           ~~~~~~~~~~^~~~~~~~\n",
      "ValueError: unsupported format character ':' (0x3a) at index 26\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 758, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 701, in shell_main\n",
      "    await self.dispatch_shell(msg, subshell_id=subshell_id)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 469, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 379, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 899, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 471, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 632, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\gimep\\AppData\\Local\\Temp\\ipykernel_14656\\32785271.py\", line 1, in <module>\n",
      "    config=ConfigurationManager()\n",
      "  File \"C:\\Users\\gimep\\AppData\\Local\\Temp\\ipykernel_14656\\1310873614.py\", line 5, in __init__\n",
      "    self.params=read_yaml(params_path)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ensure\\main.py\", line 849, in __call__\n",
      "    return_val = self.f(*args, **kwargs)\n",
      "  File \"C:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\src\\textsummarizer\\utils\\common.py\", line 27, in read_yaml\n",
      "    logger.info(f\"yaml file: {path_to_yaml} loaded successfully\")\n",
      "Message: 'yaml file: params.yaml loaded successfully'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 690, in format\n",
      "    s = self.formatMessage(record)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 659, in formatMessage\n",
      "    return self._style.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 449, in format\n",
      "    return self._format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 445, in _format\n",
      "    return self._fmt % values\n",
      "           ~~~~~~~~~~^~~~~~~~\n",
      "ValueError: unsupported format character ':' (0x3a) at index 26\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 758, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 701, in shell_main\n",
      "    await self.dispatch_shell(msg, subshell_id=subshell_id)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 469, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 379, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 899, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 471, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 632, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\gimep\\AppData\\Local\\Temp\\ipykernel_14656\\32785271.py\", line 1, in <module>\n",
      "    config=ConfigurationManager()\n",
      "  File \"C:\\Users\\gimep\\AppData\\Local\\Temp\\ipykernel_14656\\1310873614.py\", line 5, in __init__\n",
      "    self.params=read_yaml(params_path)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ensure\\main.py\", line 849, in __call__\n",
      "    return_val = self.f(*args, **kwargs)\n",
      "  File \"C:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\src\\textsummarizer\\utils\\common.py\", line 27, in read_yaml\n",
      "    logger.info(f\"yaml file: {path_to_yaml} loaded successfully\")\n",
      "Message: 'yaml file: params.yaml loaded successfully'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 690, in format\n",
      "    s = self.formatMessage(record)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 659, in formatMessage\n",
      "    return self._style.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 449, in format\n",
      "    return self._format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 445, in _format\n",
      "    return self._fmt % values\n",
      "           ~~~~~~~~~~^~~~~~~~\n",
      "ValueError: unsupported format character ':' (0x3a) at index 26\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 758, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 701, in shell_main\n",
      "    await self.dispatch_shell(msg, subshell_id=subshell_id)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 469, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 379, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 899, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 471, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 632, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\gimep\\AppData\\Local\\Temp\\ipykernel_14656\\32785271.py\", line 1, in <module>\n",
      "    config=ConfigurationManager()\n",
      "  File \"C:\\Users\\gimep\\AppData\\Local\\Temp\\ipykernel_14656\\1310873614.py\", line 6, in __init__\n",
      "    create_directories([self.config.artifacts_root])\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ensure\\main.py\", line 807, in __call__\n",
      "    return self.f(*args, **kwargs)\n",
      "  File \"C:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\src\\textsummarizer\\utils\\common.py\", line 45, in create_directories\n",
      "    logger.info(f\"created directory at: {path}\")\n",
      "Message: 'created directory at: artifacts'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 690, in format\n",
      "    s = self.formatMessage(record)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 659, in formatMessage\n",
      "    return self._style.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 449, in format\n",
      "    return self._format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 445, in _format\n",
      "    return self._fmt % values\n",
      "           ~~~~~~~~~~^~~~~~~~\n",
      "ValueError: unsupported format character ':' (0x3a) at index 26\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 758, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 701, in shell_main\n",
      "    await self.dispatch_shell(msg, subshell_id=subshell_id)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 469, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 379, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 899, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 471, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 632, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\gimep\\AppData\\Local\\Temp\\ipykernel_14656\\32785271.py\", line 1, in <module>\n",
      "    config=ConfigurationManager()\n",
      "  File \"C:\\Users\\gimep\\AppData\\Local\\Temp\\ipykernel_14656\\1310873614.py\", line 6, in __init__\n",
      "    create_directories([self.config.artifacts_root])\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ensure\\main.py\", line 807, in __call__\n",
      "    return self.f(*args, **kwargs)\n",
      "  File \"C:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\src\\textsummarizer\\utils\\common.py\", line 45, in create_directories\n",
      "    logger.info(f\"created directory at: {path}\")\n",
      "Message: 'created directory at: artifacts'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 690, in format\n",
      "    s = self.formatMessage(record)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 659, in formatMessage\n",
      "    return self._style.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 449, in format\n",
      "    return self._format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 445, in _format\n",
      "    return self._fmt % values\n",
      "           ~~~~~~~~~~^~~~~~~~\n",
      "ValueError: unsupported format character ':' (0x3a) at index 26\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 758, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 701, in shell_main\n",
      "    await self.dispatch_shell(msg, subshell_id=subshell_id)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 469, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 379, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 899, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 471, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 632, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\gimep\\AppData\\Local\\Temp\\ipykernel_14656\\32785271.py\", line 2, in <module>\n",
      "    data_ingestion_config=config.get_data_ingestion_config()\n",
      "  File \"C:\\Users\\gimep\\AppData\\Local\\Temp\\ipykernel_14656\\1310873614.py\", line 10, in get_data_ingestion_config\n",
      "    create_directories([config.root_dir])\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ensure\\main.py\", line 807, in __call__\n",
      "    return self.f(*args, **kwargs)\n",
      "  File \"C:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\src\\textsummarizer\\utils\\common.py\", line 45, in create_directories\n",
      "    logger.info(f\"created directory at: {path}\")\n",
      "Message: 'created directory at: artifacts/data_ingestion'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 690, in format\n",
      "    s = self.formatMessage(record)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 659, in formatMessage\n",
      "    return self._style.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 449, in format\n",
      "    return self._format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 445, in _format\n",
      "    return self._fmt % values\n",
      "           ~~~~~~~~~~^~~~~~~~\n",
      "ValueError: unsupported format character ':' (0x3a) at index 26\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 758, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 701, in shell_main\n",
      "    await self.dispatch_shell(msg, subshell_id=subshell_id)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 469, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 379, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 899, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 471, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 632, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\gimep\\AppData\\Local\\Temp\\ipykernel_14656\\32785271.py\", line 2, in <module>\n",
      "    data_ingestion_config=config.get_data_ingestion_config()\n",
      "  File \"C:\\Users\\gimep\\AppData\\Local\\Temp\\ipykernel_14656\\1310873614.py\", line 10, in get_data_ingestion_config\n",
      "    create_directories([config.root_dir])\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ensure\\main.py\", line 807, in __call__\n",
      "    return self.f(*args, **kwargs)\n",
      "  File \"C:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\src\\textsummarizer\\utils\\common.py\", line 45, in create_directories\n",
      "    logger.info(f\"created directory at: {path}\")\n",
      "Message: 'created directory at: artifacts/data_ingestion'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 690, in format\n",
      "    s = self.formatMessage(record)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 659, in formatMessage\n",
      "    return self._style.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 449, in format\n",
      "    return self._format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 445, in _format\n",
      "    return self._fmt % values\n",
      "           ~~~~~~~~~~^~~~~~~~\n",
      "ValueError: unsupported format character ':' (0x3a) at index 26\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 758, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 701, in shell_main\n",
      "    await self.dispatch_shell(msg, subshell_id=subshell_id)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 469, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 379, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 899, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 471, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 632, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\gimep\\AppData\\Local\\Temp\\ipykernel_14656\\32785271.py\", line 5, in <module>\n",
      "    data_ingestion.download_file()\n",
      "  File \"C:\\Users\\gimep\\AppData\\Local\\Temp\\ipykernel_14656\\3467534831.py\", line 13, in download_file\n",
      "    logger.info(f\"File already exits\")\n",
      "Message: 'File already exits'\n",
      "Arguments: ()\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 1110, in emit\n",
      "    msg = self.format(record)\n",
      "          ^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 953, in format\n",
      "    return fmt.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 690, in format\n",
      "    s = self.formatMessage(record)\n",
      "        ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 659, in formatMessage\n",
      "    return self._style.format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 449, in format\n",
      "    return self._format(record)\n",
      "           ^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Python311\\Lib\\logging\\__init__.py\", line 445, in _format\n",
      "    return self._fmt % values\n",
      "           ~~~~~~~~~~^~~~~~~~\n",
      "ValueError: unsupported format character ':' (0x3a) at index 26\n",
      "Call stack:\n",
      "  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\traitlets\\config\\application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelapp.py\", line 758, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\tornado\\platform\\asyncio.py\", line 211, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\base_events.py\", line 607, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\base_events.py\", line 1922, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Python311\\Lib\\asyncio\\events.py\", line 80, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 701, in shell_main\n",
      "    await self.dispatch_shell(msg, subshell_id=subshell_id)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 469, in dispatch_shell\n",
      "    await result\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 379, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\kernelbase.py\", line 899, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\ipkernel.py\", line 471, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\ipykernel\\zmqshell.py\", line 632, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3116, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3171, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\async_helpers.py\", line 128, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3394, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3639, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"c:\\Users\\gimep\\Downloads\\workspace\\text_summarizer\\.textenv\\Lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3699, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"C:\\Users\\gimep\\AppData\\Local\\Temp\\ipykernel_14656\\32785271.py\", line 5, in <module>\n",
      "    data_ingestion.download_file()\n",
      "  File \"C:\\Users\\gimep\\AppData\\Local\\Temp\\ipykernel_14656\\3467534831.py\", line 13, in download_file\n",
      "    logger.info(f\"File already exits\")\n",
      "Message: 'File already exits'\n",
      "Arguments: ()\n"
     ]
    }
   ],
   "source": [
    "config=ConfigurationManager()\n",
    "data_ingestion_config=config.get_data_ingestion_config()\n",
    "data_ingestion=DataIngestion(config=data_ingestion_config)\n",
    "\n",
    "data_ingestion.download_file()\n",
    "data_ingestion.extract_zip_file()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".textenv (3.11.6)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
